### ISSUE TITLE
python bindings crash at import (linux/mac) 

### ISSUE THREAD

**Issue by maweigert** [AdaptiveParticles/LibAPR#102]
Hi,

First, thanks for the great package, which I would love to use from within python.
I followed the install instructions for python support (`cmake -DAPR_BUILD_PYTHON_WRAPPERS=ON ..`) and everything builds fine. However if I try to import the built python module (`pyApr.so`) via `import pyApr` it crashes at (1) Mac and (2) Linux with the following errors:

(1) OSX 10.12.6, clang 8.0.0, python 3.6.4

```
Termination Signal:    Illegal instruction: 4
dyld: in dlopen()
BUG IN LIBTRACE: MH not found
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_trace.dylib         	0x00007fff9c24de97 _os_trace_image_was_unloaded + 271
1   dyld                          	0x000000010f2cacb2 dyld::removeImage(ImageLoader*) + 343
```

(2) Ubuntu 16.04, gcc 6.4.0, python 3.5.2
```
ImportError: /home/mweigert/cpp/LibAPR/build/pyApr.so: undefined symbol: _Py_ZeroStruct
```

**Comment by skalarproduktraum** [comment]
Hi @maweigert, could it be that the build system picked up Python 2 by accident?

**Comment by krzysg** [comment]
Python 2 is used by default, check that line in CMakeLists.txt file:
`
set(PYBIND11_PYTHON_VERSION 2.7)
`

**Comment by maweigert** [comment]
Ok, thanks! Seems like that solved the issue :)

Changing the respective line to

 `set(PYBIND11_PYTHON_VERSION 3.6)` 

in CMakeLists.txt actually works! 
Maybe that should be on the Readme?

Thanks again!
