### ISSUE TITLE
libtif version

### ISSUE THREAD

**Issue by psteinb** [AdaptiveParticles/LibAPR#113]
Just wondering why you need libtiff 5+, I see especially on windows that many package managers ship libtiff `4.0.9`. Did you test if libapr works with libtiff4 ?

**Comment by psteinb** [comment]
Just to give a reference, the source code available [here](http://download.osgeo.org/libtiff/) lists `4.0.10` as the most recent version.

**Comment by cheesema** [comment]
Thanks for querying this. Afaik this is just a typo in the Readme

**Comment by cheesema** [comment]
It works with LibTiff4, and I thats what we are all using.

**Comment by cheesema** [comment]
Updated, and in pull request for develop. Thanks Peter :)
