### ISSUE TITLE
Segmentation fault on tiff stacks

### ISSUE THREAD

**Issue by HazenBabcock** [AdaptiveParticles/LibAPR#124]
Hello,

I'm interested in how much compression I can get using this approach on tiff stacks, but I'm having some trouble with segmentation faults. `Example_get_apr` works fine for tiff stacks that have 2 images (created using the Python `tifffile` library):

```
$ ~/Code/LibAPR/build/examples/Example_get_apr -i m012_00.tif -d ./ 
Opening file: [./m012_00.tif]
TIFFFetchNormalTag: Warning, ASCII value for tag "ImageDescription" does not end in null byte.
getMesh: PixelData: size(Y/X/Z)=2048/2048/2 vSize:8388608 vCapacity:8388608 elementSize:2
getMesh: ScanlineSize=4096 StripSize=8192 NumberOfStrips=1024
TIFFFetchNormalTag: Warning, ASCII value for tag "ImageDescription" does not end in null byte.
compute_gradient_magnitude_using_bsplines took 0.050697 seconds
compute_local_intensity_scale took 0.008655 seconds
compute_levels took 0.001312 seconds
initialize_particle_cell_tree took 0.001647 seconds
compute_local_particle_set took 0.002173 seconds
compute_pulling_scheme took 0.018755 seconds
downsample_pyramid took 0.007401 seconds
compute_apr_datastructure took 0.004772 seconds
Total number of particles: 8364233
sample_particles took 0.022856 seconds
Total_pipeline_excluding_IO took 0.124207 seconds

Original image size: 16.7772 MB
Writing the APR to hdf5...
access_data took 0.001845 seconds
intensities took 0.369110 seconds
HDF5 Total Filesize: 10.9996 MB
Writing Complete
writing output took 0.374725 seconds

Computational Ratio (Pixels/Particles): 1.00291
Lossy Compression Ratio: 1.52526
```

But when I try a tiff stack that has 3 images I get a segmentation fault.

```
$ ~/Code/LibAPR/build/examples/Example_get_apr -i m012_00.tif -d ./ 
Opening file: [./m012_00.tif]
TIFFFetchNormalTag: Warning, ASCII value for tag "ImageDescription" does not end in null byte.
getMesh: PixelData: size(Y/X/Z)=2048/2048/3 vSize:12582912 vCapacity:12582912 elementSize:2
getMesh: ScanlineSize=4096 StripSize=8192 NumberOfStrips=1024
TIFFFetchNormalTag: Warning, ASCII value for tag "ImageDescription" does not end in null byte.
compute_gradient_magnitude_using_bsplines took 0.048957 seconds
Segmentation fault (core dumped)
```

Any idea what I might be doing wrong?

**Comment by joeljonsson** [comment]
Hi,

This is most likely an old bug in the computation of the local intensity scale. It has long been fixed, but unfortunately we have not updated the master branch in forever... It will be updated soon!

In the meantime, could you give it a try on the `develop` branch? 

Also, you don't seem to be getting any adaptation in the first case (2 z-slices) as the computational ratio (number pixels / number particles) is close to unity. There are quite a few parameters that influence this, and the default values in the example script probably don't work very well. You can find more information about the parameters in [the supplementary material of the paper](https://static-content.springer.com/esm/art%3A10.1038%2Fs41467-018-07390-9/MediaObjects/41467_2018_7390_MOESM1_ESM.pdf) (supplementary note 14). There is also an option to automatically select some of the most important parameters. But for some reason this is not included in the command line options for `Example_get_apr`. To quickly try this out you can add the line
```
aprConverter.par.auto_parameters = true;
```
(assuming you are on `develop`) to `Example_get_apr.cpp`, somewhere around line 60 where the other parameters are set in the `runAPR` function.

Hope this helps!

**Comment by HazenBabcock** [comment]
Thanks! Using the development branch works.

Does `auto_parameters = true` optimize for something? Maximum compression?

**Comment by joeljonsson** [comment]
Great! 

Oh no, it's just an ad hoc solution that computes "reasonable" values for the `sigma_th` and `grad_th` parameters. If these values are set too low the APR will adapt to noise, resulting in oversampling. Conversely, if they are set too high, dim or fine-grained structures may be ignored. The optimal setting is of course one such that all "wanted" signal is resolved and anything else is not, which is image- / problem-specific and rather subjective.

With `auto_parameters` enabled, the parameter values are computed by thresholding histograms of the local intensity scale (sigma) and image gradient. You could start with these values and then manually change them to see what happens (while checking that the reconstructed pixel image looks good). 

Other useful parameters that you can set via the command line arguments to `Example_get_apr` include:
`-rel_error`: the maximum relative error allowed when reconstructing the pixel image (typically 0.08-0.15)
`-I_th`: regions with intensities below this value will be ignored
`-lambda`: controls the amount of smoothing in the BSpline fitting (higher = more smoothing, for "typical" SNR ranges values are in the range 0.5-4 tend to work well)

I know it's a bit tedious to tune this at the moment. In the python wrapper of the upcoming new release there will be a tool that lets you do this interactively with a visual aid showing the structures that will be resolved.

**Comment by HazenBabcock** [comment]
Looking forward to the python wrapper :).

Which parameter does `sigma_th` correspond to? `SNR_min`?

**Comment by joeljonsson** [comment]
Oh boy, looks like that's missing too. For a quick solution you could edit line 59 of the script to
`aprConverter.par.sigma_th = options.min_signal;`
and give it in as the `-min_signal` argument (pretty sure that parameter isn't used anymore).

**Comment by HazenBabcock** [comment]
Okay, thanks for all the help with this.
