### ISSUE TITLE
Request: Include ExtraParticleData and APRAccess classes in python wrapper

### ISSUE THREAD

**Issue by bryantChhun** [AdaptiveParticles/LibAPR#129]
From what I can tell, the python wrapper includes access only to APR read/write functions, plus parameters for the APR conversion.  I'm interested in using the particle data itself, as I'm sure many others would be interested.

Is there a way to access this directly from the hdf5 file without using ExtraParticleData and APRAccess classes?

**Comment by cheesema** [comment]
@joeljonsson has actually extensively developed the python wrappers, however I don' think they are public currently. @joeljonsson could we maybe give bryant access?

**Comment by cheesema** [comment]
Apologies for the long delay in response.

**Comment by bryantChhun** [comment]
@joeljonsson Hi Joel.  I'm aware of your APRNet work and am glad you've been working on the wrappers!  If you can provide access to your fork, or maybe, submit a PR here, that'd be greatly appreciated.

**Comment by joeljonsson** [comment]
@bryantChhun so sorry for the late response. I'm happy (and somewhat surprised) you've heard of my work! I've invited you to the repository (try branching off of develop_joel, and see the instructions.md file for a quick setup guide). Feel free to contact me if you run into trouble, or if you need assistance wrapping/implementing additional functionality. I will try to make a final sweep and open the repository up to the public by the end of this week.
