### ISSUE TITLE
Integer under- and overflow due to bsplines may result in erroneous adaptation without warning

### ISSUE THREAD

**Issue by joeljonsson** [AdaptiveParticles/LibAPR#152]
For integer type images (uint8 and uint16) with intensities close to the maximum value, the bspline offset will cause overflow and value wrapping. Moreover, even if there is no overflow due to the offset itself, the bspline computation may still result in both under- and overflow. These issues can have a significant effect on the resulting adaptation -- but since no warnings are given, and the particles are sampled from the original pixels, they can be difficult to detect.

I'm not sure how to best handle this, but it would be good to at least warn the user when it occurs. We can easily check the maximum pixel value before applying the offset, and out-of-range values in the bspline computation could e.g. be detected in the [round function](https://github.com/AdaptiveParticles/LibAPR/blob/996b2050a3ce3ae41af0b7e08515c39cc393024b/src/algorithm/ComputeGradient.hpp#L222). Of course, this will impact the computation time, so it should probably be optional (but perhaps the default?).

Now, if we do implement these checks, there is still the question of what to do when out-of-range values are detected. Some potential options that I can think of would be to:
1. clip or mirror out-of-range values to avoid the wrap-around behavior of unsigned integer types.
2. squash the values to a narrower range.
3. force `lambda=0` (i.e. skip the bsplines).
4. switch to float buffers (`APRConverter<float>`)
5. exit / throw and leave it up to the user to modify the input and/or converter type.

Any thoughts on this?

**Comment by cheesema** [comment]
My vote would be for: 5, with an error suggesting 4.
