### ISSUE TITLE
APRNumerics::compute_gradient_vector() fails to calculate gradient for last particle

### ISSUE THREAD

**Issue by skalarproduktraum** [AdaptiveParticles/LibAPR#50]
It seems that APRNumerics::compute_gradient_vector() is missing the last particle in the dataset. I can consistently reproduce this with all the datasets I have, and the Java wrappers.

**Comment by krzysg** [comment]
Is this still a problem? If yes, how to reproduce it?

**Comment by cheesema** [comment]
Let me have a play, and see if its still an issue. Was when using the file from Scenery.

**Comment by cheesema** [comment]
@skalarproduktraum lets remember to check this :)
