### ISSUE TITLE
calc_sat_mean_z method calculates wrong values when used offset is close to img dimension

### ISSUE THREAD

**Issue by krzysg** [AdaptiveParticles/LibAPR#84]
I have noticed that when comparing to GPU version when z-direction was equal to 7 and offset equal to 3 in the output of calc_sat_mean_z there is a lot of 0's. When z-dir length is big enough (like 13) everything seems to be correct.

**Comment by cheesema** [comment]
This is undetstandable, given the effective stencil size of the filter across all steps. My suggestion would be that the z-direction is turned off given a two small image. But, we can see if we come up with a more elegant solution. The other is that also then the window is reduced as much as possible so it still works. However, I am not sure that is consistent with what the filter is meant to be doing.

**Comment by cheesema** [comment]
@krzysg with the introduction of the padding functionality for the local instensity scale, is this still an issue?
