### ISSUE TITLE
Java wrappers does not built anymore (-DAPR_BUILD_JAVA_WRAPPERS=ON)

### ISSUE THREAD

**Issue by krzysg** [AdaptiveParticles/LibAPR#93]
Example error output:

```
make[1]: *** Waiting for unfinished jobs....
In file included from /Users/krzysg/APR/AdaptiveParticleRepresentation/src/main/java/de/mpicbg/mosaic/apr/libaprJAVA_wrap.cxx:237:
/usr/local/Cellar/llvm/6.0.0/include/c++/v1/vector:1359:9: error: no matching member function for call to 'assign'
        assign(__x.__begin_, __x.__end_);
```

I have no idea when it started to failing (I have checked several branches going back in time like 2 weeks but fails on all of them).

So the main things that should be addressed here are:
- obviously we need fix (or decision to abandon swig and go with JavaCPP)
- we should somehow add build of java wrappers to travis to avoid such situations in future

**Comment by cheesema** [comment]
I would support abandoning swig and going with JavaCPP, @skalarproduktraum what is your opinion?

**Comment by skalarproduktraum** [comment]
I would agree with @cheesema when we can do the same with JavaCPP (as in have the full APR classes wrapped with JavaCPP). Happy to do this together with @krzysg e.g. next week :+1:

**Comment by cheesema** [comment]
These wrappers have been replaced by JavaCPP wrappers see: https://github.com/AdaptiveParticles/LibAPR-java-wrapper

**Comment by krzysg** [comment]
Should we remove java SWIG stuff from LibAPR?

**Comment by cheesema** [comment]
My vote would be yes?

**Comment by krzysg** [comment]
These wrappers were used only by @skalarproduktraum, Ulrik do you still need them in LibAPR? If not I will remove them.

**Comment by skalarproduktraum** [comment]
I will check the new wrappers in the next days and see if there's still something needed there. If you, you can delete them. I'll get back to you later this week 👍

**Comment by krzysg** [comment]
[LibAPR-java-wrapper](https://github.com/AdaptiveParticles/LibAPR-java-wrapper) is the replacement for swig java wrappers which is currently supported (and used in other projects). SWIG has been removed from LibAPR.
